### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by t00m** [radomirbosak/duden#121]
**Describe the bug**
export() method failed while exporting a result.

**To Reproduce**
>>> import duden
>>> w = duden.get('gerne')
>>> print(w)
None
>>> matches = duden.search('gerne', exact=False)
>>> len(matches)
12
print(matches)
[gern, auch, besonders süddeutsch: gerne (Adverb), gernhaben (unregelmäßiges Verb), gern gesehen, gerngesehen (Adjektiv), allzu gern (None), lieber (None), liebste, liebster, liebstes (Adjektiv), Gernegroß, der (Substantiv, maskulin), Gerneklug, der (Substantiv, maskulin), wälgern, auch welgern (schwaches Verb), ungern (Adverb), schlägern (schwaches Verb), ärgern (schwaches Verb)]
>>> w = matches[0]
>>> w.export()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t00m/.local/lib/python3.8/site-packages/duden/word.py", line 293, in export
    worddict[attribute] = getattr(self, attribute, None)
  File "/home/t00m/.local/lib/python3.8/site-packages/duden/word.py", line 59, in name
    name, _ = self.title.split(', ')
ValueError: too many values to unpack (expected 2)
>>> w = matches[1]
>>> w.export()
{'name': 'gernhaben', 'urlname': 'gernhaben', [...]}

**Expected behavior**
Get a dictionary with the results.

**Version**
duden 0.14.0
Python 3.8.6
Ubuntu 20.10

**Notes**
First time I get this error after checking a few dozens of words.
I found your library yesterday. I haven't had enough time to look in deep into the code yet.
By the way, thank you so much for this superb library!

**Comment by radomirbosak** [comment]
Fixed by https://github.com/radomirbosak/duden/pull/124

The change is now live in pypi too.
```
pip3 install --upgrade duden
```
