### ISSUE TITLE
Do not cache if it throws error

### ISSUE THREAD

**Issue by Joshix-1** [radomirbosak/duden#130]
Do not cache the result if it is `Not a gzipped file (b'Yt')` becuase when retrying it with the --no-cache flag it often works. But then I have to always use the flag for these certain words that failed the first time.

**Comment by radomirbosak** [comment]
Thanks for creating this issue.

May I know under what conditions and how often is a corrupt cache created?
Depending on this we might be able to prevent the cache to be created in the first place.

For now, what we can do is to not use the cache if it's corrupted, as you suggested. (= in code, passing an `IOError`)

Other mitigations could be commandline switches such as 
* `--clear-cache` to delete all cache (basically `rm ~/.cache/duden/*`)
* `--fix-cache` - try to open all `.gz` files in `~/.cache/duden/` and those which fail would be deleted.

**Comment by radomirbosak** [comment]
I merged a fix and pushed it to pypi too. Let me know if it helped.
