### ISSUE TITLE
Provide a warning message when user tries to use the disfunctional ".grammar" property and "--grammar" CLI option

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/duden#194]
The grammar CLI and property were removed in PR https://github.com/radomirbosak/duden/pull/176

**Comment by ackhh** [comment]
I'm very happy to hear the duden project is not "dead".

**Comment by radomirbosak** [comment]
Released in [0.19.1](https://pypi.org/project/duden/0.19.1/)
