### ISSUE TITLE
Does not work on python2

### ISSUE THREAD

**Issue by cansik** [radomirbosak/duden#33]
For example `Loeffel` returns an error:

```bash
>>> import duden
>>> w = duden.get('Loeffel')
>>> w
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/duden/main.py", line 60, in __repr__
    return '{} ({})'.format(self.title, self.part_of_speech)
  File "/usr/local/lib/python2.7/site-packages/duden/main.py", line 94, in title
    return self.soup.h1.get_text().replace('\xad', '')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xad in position 0: ordinal not in range(128)
```

**Comment by radomirbosak** [comment]
Hi @cansik .

Unfortunately duden doesn't support python2, only python3.

python2 support is not planned either.. but I'll gladly welcome any PRs fixing this.

**Comment by cansik** [comment]
@radomirbosak Ah ok, thank you! Would be nice if you could add the supported versions to the readme. When I have time I take a look at it and maybe create a PR.

**Comment by radomirbosak** [comment]
I just updated the readme and setup.py with the information about supported versions. Sorry that it took so long.
