### ISSUE TITLE
Add shell completion

### ISSUE THREAD

**Issue by jorgesumle** [radomirbosak/duden#56]
It's useful, you don't have to remember or look up usage information. Ideally, you should be able to press tab to autocomplete or see relevant suggestions.

**Comment by radomirbosak** [comment]
Definitely useful! But I'm not sure if python's setup.py is able to install shell completion files. In any case we can include them in the repo and include instructions for users how to install them (usually just a `cp` command).

**Comment by jorgesumle** [comment]
> But I'm not sure if python's setup.py is able to install shell completion files

I'm sure it won't work with pip. It can work with `python setup.py install` if you overwrite `setuptools.command.install`, but I don't recommend it.

> In any case we can include them in the repo and include instructions for users how to install them (usually just a cp command).

Well, we have a Makefile, we could add the targets `install` and `uninstall` to it, `make install` is an easy and simple command which should install the program correctly in any [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)-compliant OS.
