### ISSUE TITLE
Changes in duden.de broke the parsing?

### ISSUE THREAD

**Issue by lambiase** [radomirbosak/duden#77]
Hi,
when trying to search any term (for example "Löffel") I don't get any result.

In addition, many of the tests are failing for me:

```
$ make test
python --version
Python 3.7.4
python -m pytest tests/
========================================= test session starts ==========================================
platform linux -- Python 3.7.4, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/user/Documents/workspace/duden
collected 84 items                                                                                     

tests/test_online_attributes.py ..F..F...F..F........FFF.FFFFFF.FFF....F..FFFFFFFFFF.FFFFFF.FFFF [ 76%]
FF.FFF..F..FFFFF.F.F
```

Is this a known issue due to changes in the duden.de page?

**Comment by radomirbosak** [comment]
First, thanks for filing this issue. Yes, this is a known issue. I think it's been broken for more than a month now. I didn't have time to investigate or fix this bug, but it's probably, as you mentioned, due to changes to the duden.de page. PRs to fix this are more than welcome :)

**Comment by jorgesumle** [comment]
I've fixed the word search in #78

More things must be fixed.

**Comment by Garretenion** [comment]
I assume, this is sadly still broken? I figured this out today and have the same trouble as lambiase :/. I don't get any result at all. Any workaround possible?

**Comment by jorgesumle** [comment]
> Any workaround possible?

No, we must fix it. I started in https://github.com/radomirbosak/duden/pull/78, but more work needs to be done and I don't have now the time to keep working on that.

**Comment by radomirbosak** [comment]
I'm adapting the code to the new format in the `fix-new-format` branch 
https://github.com/radomirbosak/duden/tree/fix-new-format

So far, title, part-of-speech, frequency and word-separation has been fixed

I'm hoping to merge this soon to the master as well.

Sorry for the extreme delay.

**Comment by radomirbosak** [comment]
Errors down to 11.
```
======================== 11 failed, 73 passed in 27.38s ========================
```
On the aforementioned branch, all attributes except for `grammar` and `meaning_overview` should work as previously. I'm working on fixing those too.

**Comment by radomirbosak** [comment]
I fixed most of the issues in the https://github.com/radomirbosak/duden/pull/79 pull request, and pushed it into master. I haven't updated the pip `duden` package yet, so make sure to install from the master branch, at least for now:

```console
git clone https://github.com/radomirbosak/duden.git
cd duden
pip3 install --user .
```

The only thing still broken is the `--meaning-overview` option. I parses the text from the correct page paragraph, but includes a lot of unneeded text, such as examples and figure labels. This still needs to be fixed. I silenced the failing tests for now and marked them as "expected to fail".

**Comment by radomirbosak** [comment]
To followup with the _meaning overview_ parameter see bug https://github.com/radomirbosak/duden/issues/80 .

**Comment by jorgesumle** [comment]
Can you publish a new release now that this is fixed?

**Comment by radomirbosak** [comment]
Version `0.12.0` published to pypi.
https://pypi.org/project/duden/0.12.0/

You should now be able to install the new version with
```console
pip3 install --user duden
```
